---
title: "Nile River Flow with Plotly"
author: "Darky"
date: "1/27/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r warning=FALSE}
# Prepare Library
library(plotly)
# Prepare Data
data("Nile")
NileQ <- quantile(Nile)
df <- data.frame(Nile=Nile,
                 firstQ=NileQ[["25%"]],
                 median=NileQ[["50%"]],
                 thirdQ=NileQ[["75%"]])
```

## Plotly Line Chart
```{r}
p <- plot_ly(data=df) %>%
  add_trace(x=time(df$Nile), y = df$Nile, name = "Flow", mode = "lines") %>%
  add_trace(x=time(df$Nile), y = df$firstQ, name = "First Quartile", 
            line=list(dash = "dash"), opacity = .6, mode = "lines") %>%
  add_trace(x=time(df$Nile), y=df$median, name="Median", 
            line=list(dash = "dash"), opacity = .6, mode = "lines") %>%
  add_trace(x=time(df$Nile), y=df$thirdQ, name="Third Quartile", 
            line=list(dash = "dash"), opacity = .6, mode = "lines") %>%
  layout(title="Annual Flow of the River Nile",
         xaxis=list(title = "Year"),
         yaxis=list(title = "Volume"))
p
```